apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0      
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      serviceAccountName: default
      containers:
        - name: paymentservice
          image: vzaletny/hipster_shop_payment:v0.0.2 
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"
